# Generated by Django 5.0.7 on 2025-10-09 19:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('curso', models.CharField(choices=[('Administração', 'administração'), ('Controle Ambiental', 'controle ambiental'), ('Edificações', 'edificações'), ('Eletrotécnica', 'eletrotécnica'), ('Geologia', 'geologia'), ('Informática para Internet', 'informática para internet'), ('Manutenção e Suporte em Informática', 'manutenção e suporte'), ('Mecânica', 'mecânica'), ('Mineração', 'mineração'), ('Controle Ambiental (Subsequente)', 'controle ambiental subsequente'), ('Edificações (Subsequente)', 'edificações subsequente'), ('Eletrotécnica (Subsequente)', 'eletrotécnica subsequente'), ('Geologia (Subsequente)', 'geologia subsequente'), ('Mecânica (Subsequente)', 'mecânica subsequente'), ('Mineração (Subsequente)', 'mineração subsequente'), ('Petróleo e Gás (Subsequente)', 'petróleo e gás subsequente'), ('Redes de Computadores (Subsequente)', 'redes de computadores subsequente'), ('Manutenção e Suporte em Informática (Subsequente)', 'manutenção suporte subsequente'), ('Informática (Subsequente)', 'informática subsequente'), ('Segurança do Trabalho (Subsequente)', 'segurança do trabalho subsequente'), ('Estradas (Subsequente)', 'estradas subsequente'), ('Implantação de Serviços VoIP (FIC)', 'implantacao servicos voip fic'), ('Aplicador de Revestimento Cerâmico (FIC)', 'aplicador revestimento ceramico fic'), ('Artesanato com Material Reciclável (FIC)', 'artesanato material reciclavel fic'), ('Engenharia Civil', 'engenharia civil'), ('Engenharia de Energia', 'engenharia de energia'), ('Engenharia Sanitária e Ambiental', 'engenharia sanitária e ambiental'), ('Tecnologia em Análise e Desenvolvimento de Sistemas', 'tecnologia ads'), ('Tecnologia em Comércio Exterior', 'tecnologia comércio exterior'), ('Tecnologia em Gestão Pública', 'tecnologia gestão pública'), ('Tecnologia em Redes de Computadores', 'tecnologia redes de computadores'), ('Especialização em Engenharia de Segurança do Trabalho', 'esp segurança trabalho'), ('Especialização em Ensino de Geociências', 'esp ensino geociências'), ('Especialização em Gestão Ambiental', 'esp gestão ambiental'), ('Mestrado Profissional em Ensino de Física', 'mestrado prof ensino física'), ('Mestrado Profissional em Uso Sustentável de Recursos Naturais', 'mestrado prof recursos naturais'), ('Doutorado Acadêmico em Educação Profissional', 'doutorado educação profissional')], max_length=100, verbose_name='Curso')),
                ('periodo', models.IntegerField(verbose_name='Período')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssistenteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Apodi', 'Apodi'), ('Caico', 'Caicó'), ('Canguaretama', 'Canguaretama'), ('CearaMirim', 'Ceará-Mirim'), ('CurraisNovos', 'Currais Novos'), ('Ipanguacu', 'Ipanguaçu'), ('JoaoCamara', 'João Câmara'), ('Jucurutu', 'Jucurutu'), ('Lajes', 'Lajes'), ('Macau', 'Macau'), ('Mossoro', 'Mossoró'), ('NatalCentral', 'Natal-Central'), ('NatalCidadeAlta', 'Natal-Cidade Alta'), ('NatalZonaNorte', 'Natal-Zona Norte'), ('NovaCruz', 'Nova Cruz'), ('Parelhas', 'Parelhas'), ('Parnamirim', 'Parnamirim'), ('PauDosFerros', 'Pau dos Ferros'), ('SantaCruz', 'Santa Cruz'), ('SaoGoncaloDoAmarante', 'São Gonçalo do Amarante'), ('SaoPauloDoPotengi', 'São Paulo do Potengi')], max_length=100)),
                ('qtd_participantes', models.IntegerField(blank=True, null=True)),
                ('qtd_chamados', models.IntegerField(blank=True, null=True)),
                ('impedir_aluno', models.BooleanField(default=False)),
                ('exigir_comprov', models.BooleanField(default=False)),
                ('exigir_frequen', models.BooleanField(default=False)),
                ('disponibilidade', models.BooleanField(default=False)),
                ('edital', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auxilio',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('tipo', models.CharField(choices=[('auxilio transporte', 'Auxílio transporte'), ('auxilio moradia', 'Auxílio moradia'), ('alimentação estudantil', 'Alimentação estudantil'), ('apoio a formação estudantil', 'Apoio a formação estudantil'), ('auxilios eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='auxilio transporte', max_length=30)),
                ('solicitados', models.CharField(choices=[('Todos', 'todos'), ('Todos inscritos no programa', 'todos inscritos no programa'), ('Selecionar alunos', 'selecionar alunos')], default='todos', max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_formulario', models.IntegerField()),
                ('alunos_solicitados', models.IntegerField()),
                ('sem_resposta', models.IntegerField()),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_auxilio', models.CharField(choices=[('auxilio transporte', 'Auxílio transporte'), ('auxilio moradia', 'Auxílio moradia'), ('alimentação estudantil', 'Alimentação estudantil'), ('apoio a formação estudantil', 'Apoio a formação estudantil'), ('auxilios eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=50)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('id_auxilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_auxilio', to='API.auxilio')),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo_de_chamado', models.CharField(choices=[('Alteração de documentos', 'alteracao de documentos'), ('Arquivos pendentes', 'arquivos pendentes'), ('Justificação', 'justificacao'), ('Outro', 'outro')], default='alteracao de documentos', max_length=25)),
                ('tipo_de_auxilio', models.CharField(choices=[('auxilio transporte', 'Auxílio transporte'), ('auxilio moradia', 'Auxílio moradia'), ('alimentação estudantil', 'Alimentação estudantil'), ('apoio a formação estudantil', 'Apoio a formação estudantil'), ('auxilios eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='auxilio transporte', max_length=30)),
                ('status', models.BooleanField()),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_analise', models.DateField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.aluno', verbose_name='chamados')),
                ('assistente_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.assistentesocial', verbose_name='chamados')),
            ],
            options={
                'db_table': 'chamado',
            },
        ),
        migrations.CreateModel(
            name='FormularioQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pergunta', models.CharField(max_length=250)),
                ('tipo_pergunta', models.CharField(choices=[('paragrafo', 'Parágrafo'), ('multipla_escolha', 'Múltipla escolha'), ('caixa_selecao', 'Caixas de seleção')], default='multipla escolha', max_length=50)),
                ('obrigatoriedade', models.BooleanField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='API.formulario')),
            ],
            options={
                'db_table': 'formulario_questao',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FormularioQuestaoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(max_length=250)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='API.formularioquestao')),
            ],
            options={
                'db_table': 'formulario_questao_opcao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=900)),
                ('resposta', models.CharField(blank=True, max_length=900, null=True)),
                ('status', models.CharField(choices=[('Respondida', 'respondida'), ('Não respondida', 'nao respondida')], max_length=100)),
                ('data_realizacao', models.DateField(auto_now_add=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.aluno')),
                ('assistente_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.assistentesocial')),
            ],
            options={
                'db_table': 'pergunta',
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.aluno')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='API.formulario')),
            ],
            options={
                'db_table': 'resposta_formulario',
                'unique_together': {('formulario', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em analise', 'Em Análise'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido'), ('deferido sem recurso', 'Deferido sem recurso')], default='em analise', max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_deferimento', models.DateField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aluno', to='API.aluno')),
                ('id_assistente_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_AS', to='API.assistentesocial')),
                ('id_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_beneficio', to='API.beneficio')),
            ],
            options={
                'db_table': 'solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RG', 'rg'), ('CPF', 'cpf'), ('Comprovante de residência', 'comprovante de residencia'), ('Histórico escolar', 'historico escolar'), ('Comprovante de renda', 'comprovante de renda'), ('Comprovante de ausência de renda', 'comprovante de ausencia de renda'), ('Outros', 'outros')], max_length=35)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.aluno')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.solicitacao')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, null=True)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('Enviada', 'enviada'), ('Não lida', 'nao lida'), ('Lida', 'lida')], max_length=20)),
                ('data_visualizacao', models.DateField(blank=True, null=True)),
                ('usuario', models.ManyToManyField(related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
        migrations.AddField(
            model_name='assistentesocial',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistentesocial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_aberta', models.TextField(blank=True, null=True)),
                ('opcao_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.formularioquestaoopcao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.formularioquestao')),
                ('resposta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questoes', to='API.respostaformulario')),
            ],
            options={
                'db_table': 'resposta_questao',
                'unique_together': {('resposta_formulario', 'questao')},
            },
        ),
    ]
